[workspace.package]
version = "1.1.7"
authors = [
    "Thomas Lamprecht <t.lamprecht@proxmox.com>",
    "Proxmox Support Team <support@proxmox.com>",
]
edition = "2021"
license = "AGPL-3"
repository = "https://git.proxmox.com/?p=proxmox-datacenter-manager.git"

exclude = [ "build" ]

[workspace]
resolver = "2"
members = [
    "lib/pdm-buildcfg",

    "server",
    "lib/pdm-api-types",
    "lib/pdm-client",
    "lib/pdm-config",
    "lib/pdm-search",
    "lib/pdm-ui-shared",

    "cli/client",
    "cli/admin",
    "cli/proxmox-fido2",
]

[workspace.dependencies]
# proxmox workspace
proxmox-access-control = "1"
proxmox-api-macro = "1.3"
proxmox-apt-api-types = "3.0"
proxmox-async = "0.5"
proxmox-auth-api = "1.0.5"
proxmox-base64 = "1"
proxmox-client = "1.0.4"
proxmox-daemon = "1"
proxmox-docgen = "1"
proxmox-http = { version = "1.0.4", features = [ "client", "http-helpers", "websocket" ] } # see below
proxmox-human-byte = "1"
proxmox-io = "1.0.1" # tools and client use "tokio" feature
proxmox-ldap = { version = "1.1", features = ["sync"] }
proxmox-lang = "1.1"
proxmox-log = "1"
proxmox-login = "1.0.2"
proxmox-rest-server = "1"
# some use "cli", some use "cli" and "server", pbs-config uses nothing
proxmox-router = { version = "3.0.0", default-features = false }
proxmox-rrd = { version = "1", default-features = false}
proxmox-rrd-api-types = "1.0.2"
# everything but pbs-config and pbs-client use "api-macro"
proxmox-schema = "5"
proxmox-section-config = "3"
proxmox-serde = "1"
proxmox-shared-memory = "1"
proxmox-simple-config = "1"
proxmox-sortable-macro = "1"
proxmox-subscription = { version = "1.0.2", features = [ "api-types"], default-features = false }
proxmox-sys = "1"
proxmox-tfa = { version = "6", features = [ "api-types" ], default-features = false }
proxmox-time = "2"
proxmox-uuid = "1"
proxmox-installer-types = "0.2"
proxmox-network-types = "1.1"

# other proxmox crates
proxmox-acme = "1.0"
proxmox-openid = "1.0.2"

# api implementation creates
proxmox-config-digest = "1"
proxmox-product-config = "1"
proxmox-dns-api = "1"
proxmox-acme-api = "1"

# API types for PVE (and later PMG?)
pve-api-types = "8.1.12"
# API types for PBS
pbs-api-types = { version = "1.0.9", features = [ "enum-fallback" ] }

# PDM workspace
server = { path = "server" }
pdm-api-types = { path = "lib/pdm-api-types" }
pdm-buildcfg = { path = "lib/pdm-buildcfg" }
pdm-config = { path = "lib/pdm-config" }
pdm-client = { version = "1.0", path = "lib/pdm-client" }
pdm-search = { version = "0.2", path = "lib/pdm-search" }
pdm-ui-shared = { version = "1.0", path = "lib/pdm-ui-shared" }
proxmox-fido2 = { path = "cli/proxmox-fido2" }

# regular crates
anyhow = "1.0"
async-stream = "0.3"
async-trait = "0.1"
const_format = "0.2"
futures = "0.3"
glob = "0.3"
hex = "0.4.3"
http = "1"
http-body-util = "0.1.2"
hyper = { version = "1", features = [ "full" ] }
hyper-util = "0.1"
libc = "0.2"
log = "0.4.17"
minijinja = "2.19"
nix = "0.29"
once_cell = "1.3.1"
openssl = "0.10.40"
percent-encoding = "2.1"
pin-project-lite = "0.2"
regex = "1.5.5"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0"
serde_plain = "1"
tempfile = "3.15"
thiserror = "1.0"
tokio = "1.6"
tracing = "0.1"
url = "2.1"
webauthn-rs-core = "0.5"
xdg = "2.2"
zstd = { version = "0.13" }

# Local path overrides
# NOTE: You must run `cargo update` after changing this for it to take effect!
[patch.crates-io]
# proxmox-access-control = { path = "../proxmox/proxmox-access-control" }
# proxmox-acme-api = { path = "../proxmox/proxmox-acme-api" }
# proxmox-acme = { path = "../proxmox/proxmox-acme" }
# proxmox-api-macro = { path = "../proxmox/proxmox-api-macro" }
# proxmox-apt-api-types = { path = "../proxmox/proxmox-apt-api-types" }
# proxmox-async = { path = "../proxmox/proxmox-async" }
# proxmox-auth-api = { path = "../proxmox/proxmox-auth-api" }
# proxmox-borrow = { path = "../proxmox/proxmox-borrow" }
# proxmox-client = { path = "../proxmox/proxmox-client" }
# proxmox-compression = { path = "../proxmox/proxmox-compression" }
# proxmox-config-digest = { path = "../proxmox/proxmox-config-digest" }
# proxmox-daemon = { path = "../proxmox/proxmox-daemon" }
# proxmox-dns-api = { path = "../proxmox/proxmox-dns-api" }
# proxmox-docgen = { path = "../proxmox/proxmox-docgen" }
# proxmox-http-error = { path = "../proxmox/proxmox-http-error" }
# proxmox-http = { path = "../proxmox/proxmox-http" }
# proxmox-human-byte = { path = "../proxmox/proxmox-human-byte" }
# proxmox-installer-types = { path = "../proxmox/proxmox-installer-types" }
# proxmox-io = { path = "../proxmox/proxmox-io" }
# proxmox-lang = { path = "../proxmox/proxmox-lang" }
# proxmox-ldap = { path = "../proxmox/proxmox-ldap" }
# proxmox-login = { path = "../proxmox/proxmox-login" }
# proxmox-log = { path = "../proxmox/proxmox-log" }
# proxmox-metrics = { path = "../proxmox/proxmox-metrics" }
# proxmox-network-types = { path = "../proxmox/proxmox-network-types" }
# proxmox-notify = { path = "../proxmox/proxmox-notify" }
# proxmox-openid = { path = "../proxmox/proxmox-openid" }
# proxmox-product-config = { path = "../proxmox/proxmox-product-config" }
# proxmox-rest-server = { path = "../proxmox/proxmox-rest-server" }
# proxmox-router = { path = "../proxmox/proxmox-router" }
# proxmox-rrd = { path = "../proxmox/proxmox-rrd" }
# proxmox-schema = { path = "../proxmox/proxmox-schema" }
# proxmox-section-config = { path = "../proxmox/proxmox-section-config" }
# proxmox-serde = { path = "../proxmox/proxmox-serde" }
# proxmox-shared-memory = { path = "../proxmox/proxmox-shared-memory" }
# proxmox-simple-config = { path = "../proxmox/proxmox-simple-config" }
# proxmox-sortable-macro = { path = "../proxmox/proxmox-sortable-macro" }
# proxmox-subscription = { path = "../proxmox/proxmox-subscription" }
# proxmox-sys = { path = "../proxmox/proxmox-sys" }
# proxmox-tfa = { path = "../proxmox/proxmox-tfa" }
# proxmox-time = { path = "../proxmox/proxmox-time" }
# proxmox-uuid = { path = "../proxmox/proxmox-uuid" }
# proxmox-worker-task = { path = "../proxmox/proxmox-worker-task" }
