#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
  configure)
    # For migrations or upgrade steps that can safely be automated.
    # NOTE: check if '/proxmox_install_mode' exist to avoid doing something if in the ISO installer environment.

    cfgdir="/etc/proxmox-datacenter-manager"

    if test -n "$2" && dpkg --compare-versions "$2" 'lt' '1.0~'; then
        if test -f "$cfgdir/ldap_passwords.json"; then
            echo "migrating legacy 'ldap_passwords.json' location to 'access/ldap-passwords.json'"
            mv "$cfgdir/ldap_passwords.json" "$cfgdir/access/ldap-passwords.json" || \
                echo "moving '$cfgdir/ldap_passwords.json' to '$cfgdir/access/ldap-passwords.json' failed with code $?"
        fi
    fi

    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
