[package]
name = "pdm-ui"
version = "1.1.3"
edition = "2021"
license = "AGPL-3"
repository = "https://git.proxmox.com/?p=proxmox-datacenter-manager.git"

[workspace]
resolver = "2"

[dependencies]
anyhow = "1.0"
futures = "0.3"
geojson = "0.24"
gloo-net = "0.4"
gloo-timers = "0.3"
gloo-utils = "0.2"
http = "1"
js-sys = "0.3.69"
log = "0.4.6"
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
web-sys = { version = "0.3", features = ["Location", "DataTransfer"] }
yew = { version = "0.21",  features = ["csr"] }
yew-router = { version = "0.18" }

pwt = "0.8.0"
pwt-macros = "0.5"

proxmox-yew-comp = { version = "0.8.17", features = ["apt", "dns", "network", "rrd"] }

proxmox-access-control = { version = "1.1", features = []}
proxmox-acme-api = "1"
proxmox-deb-version = "0.1"
proxmox-client = "1"
proxmox-human-byte = "1"
proxmox-installer-types = "0.2"
proxmox-login = "1"
proxmox-network-types = "1.1"
proxmox-schema = "5"
proxmox-subscription = { version = "1.0.1", features = ["api-types"], default-features = false }
proxmox-rrd-api-types = "1"
proxmox-time = "2"
pbs-api-types = { version = "1.0.3", features = [ "enum-fallback" ] }

pdm-api-types = { version = "1.0", path = "../lib/pdm-api-types" }
pdm-client = { version = "1.0", path = "../lib/pdm-client" }

pdm-ui-shared = { version = "1.0", path = "../lib/pdm-ui-shared" }

pdm-search = { version = "0.2", path = "../lib/pdm-search" }

[patch.crates-io]
# proxmox-client = { path = "../../proxmox/proxmox-client" }
# proxmox-human-byte = { path = "../../proxmox/proxmox-human-byte" }
# proxmox-installer-types = { path = "../proxmox/proxmox-installer-types" }
# proxmox-login = { path = "../../proxmox/proxmox-login" }
# proxmox-rrd-api-types = { path = "../../proxmox/proxmox-rrd-api-types" }
# proxmox-schema = { path = "../../proxmox/proxmox-schema" }
# proxmox-yew-comp = { path = "../../proxmox-yew-comp" }
# pwt = { path = "../../proxmox-yew-widget-toolkit" }
# pwt-macros = { path = "../../proxmox-yew-widget-toolkit/pwt-macros" }
